# Generated by Django 4.2 on 2026-06-05 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_type', models.CharField(choices=[('coach', '코치형'), ('practical', '실무형'), ('verifier', '검증형'), ('pressure', '압박형')], max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'persona_configs',
                'ordering': ['persona_type'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('prompt_type', models.CharField(choices=[('question_generation', 'Question Generation'), ('answer_evaluation', 'Answer Evaluation'), ('follow_up_generation', 'Follow-up Generation'), ('final_report', 'Final Report')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prompt_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('change_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='prompt.prompttemplate')),
            ],
            options={
                'db_table': 'prompt_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='default_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_templates', to='prompt.promptversion'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='persona_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to='prompt.personaconfig'),
        ),
        migrations.AddField(
            model_name='personaconfig',
            name='active_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_personas', to='prompt.prompttemplate'),
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='unique_prompt_template_version'),
        ),
    ]
