# Generated by Codex on 2026-06-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0010_interviewquestion_question_category'),
        ('prompt', '0002_remove_pressure_persona_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPromptTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_prompt_test_runs', to=settings.AUTH_USER_MODEL)),
                ('prompt_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_test_runs', to='prompt.promptversion')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_prompt_test_run', to='interview.interviewsession')),
            ],
            options={
                'db_table': 'admin_prompt_test_runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
