# Generated by Django 4.2 on 2026-06-26 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0003_adminprompttestrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptversion',
            name='activated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='feature_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='interview_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='rollback_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollback_versions', to='prompt.promptversion'),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ROLLED_BACK', 'Rolled Back')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='promptversion',
            name='test_result',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
