# Generated by Django 4.2 on 2026-06-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dormancy_warning_sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
