# Generated by Django 4.2 on 2026-06-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_dormancy_warning_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('code_hash', models.CharField(blank=True, max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('resend_available_at', models.DateTimeField()),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('is_used', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('terms_version', models.CharField(default='v1', max_length=50)),
                ('privacy_version', models.CharField(default='v1', max_length=50)),
                ('terms_agreed', models.BooleanField(default=False)),
                ('privacy_agreed', models.BooleanField(default=False)),
                ('marketing_agreed', models.BooleanField(default=False)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pending Registration',
                'verbose_name_plural': 'Pending Registrations',
                'db_table': 'accounts_pending_registration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pendingregistration',
            index=models.Index(fields=['email', 'is_used'], name='pending_email_used_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingregistration',
            index=models.Index(fields=['expires_at'], name='pending_expires_idx'),
        ),
    ]
