# Generated by Django 4.2 on 2026-06-26 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pendingregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point_balance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='point_last_updated_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('EARN', 'Earn'), ('USE', 'Use'), ('REFUND', 'Refund'), ('EXPIRE', 'Expire'), ('ADMIN', 'Admin')], max_length=20)),
                ('amount', models.IntegerField()),
                ('balance_after', models.PositiveIntegerField()),
                ('reason_code', models.CharField(max_length=80)),
                ('reference_id', models.CharField(blank=True, default='', max_length=100)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('policy_version', models.CharField(default='2026.06', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Point History',
                'verbose_name_plural': 'Point Histories',
                'db_table': 'accounts_point_history',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='pointhistory',
            index=models.Index(fields=['user', 'created_at'], name='point_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='pointhistory',
            index=models.Index(fields=['reason_code'], name='point_reason_idx'),
        ),
    ]
