# Generated by Django 4.2 on 2026-06-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pendingregistration_and_more'),
        ('accounts', '0005_user_withdrawn'),
    ]

    operations = [
    ]
