# Generated by merge resolution on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20260619_1747'),
        ('accounts', '0006_points_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attendance_record',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
