# Generated by Django 4.2 on 2026-06-26 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_points_withdrawal_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointPolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason_code', models.CharField(max_length=80, unique=True)),
                ('transaction_type', models.CharField(choices=[('EARN', 'Earn'), ('USE', 'Use'), ('REFUND', 'Refund'), ('EXPIRE', 'Expire'), ('ADMIN', 'Admin')], max_length=20)),
                ('amount', models.IntegerField()),
                ('daily_limit', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('monthly_limit', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('account_once', models.BooleanField(default=False)),
                ('per_reference_once', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('policy_version', models.CharField(default='2026.06', max_length=30)),
                ('effective_start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_end_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'point_policies',
                'ordering': ['reason_code'],
            },
        ),
        migrations.CreateModel(
            name='PointPolicyChangeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('before_value', models.JSONField(blank=True, default=dict)),
                ('after_value', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'point_policy_change_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('kakao', 'Kakao')], max_length=20)),
                ('provider_user_id', models.CharField(max_length=191)),
                ('provider_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'social_accounts',
                'ordering': ['provider', 'provider_user_id'],
            },
        ),
        migrations.CreateModel(
            name='TermsAgreement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('TERMS', 'Terms'), ('PRIVACY', 'Privacy'), ('MARKETING', 'Marketing')], max_length=30)),
                ('version', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('agreed', models.BooleanField(default=True)),
                ('agreed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('SIGNUP', 'Signup'), ('MYPAGE', 'Mypage'), ('ADMIN', 'Admin')], default='SIGNUP', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'terms_agreements',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TermsDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('TERMS', 'Terms'), ('PRIVACY', 'Privacy'), ('MARKETING', 'Marketing')], max_length=30)),
                ('version', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('content_hash', models.CharField(blank=True, default='', max_length=128)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retired_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('retention_policy', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'terms_documents',
                'ordering': ['kind', '-effective_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='termsdocument',
            index=models.Index(fields=['kind', 'is_active'], name='terms_kind_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='termsdocument',
            constraint=models.UniqueConstraint(fields=('kind', 'version'), name='unique_terms_document_version'),
        ),
        migrations.AddField(
            model_name='termsagreement',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='accounts.termsdocument'),
        ),
        migrations.AddField(
            model_name='termsagreement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointpolicychangelog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_policy_change_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointpolicychangelog',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='accounts.pointpolicy'),
        ),
        migrations.AddField(
            model_name='pointpolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_point_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='termsagreement',
            index=models.Index(fields=['user', 'kind'], name='terms_user_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='termsagreement',
            index=models.Index(fields=['user', 'created_at'], name='terms_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='socialaccount',
            index=models.Index(fields=['provider', 'provider_email'], name='social_provider_email_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='unique_social_provider_user'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_social_provider'),
        ),
        migrations.AddIndex(
            model_name='pointpolicy',
            index=models.Index(fields=['reason_code', 'is_active'], name='point_policy_active_idx'),
        ),
        migrations.AddIndex(
            model_name='pointpolicy',
            index=models.Index(fields=['effective_start_at', 'effective_end_at'], name='point_policy_period_idx'),
        ),
    ]
