# Generated by Django 4.2 on 2026-06-10 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_feedback_reports_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalreport',
            options={'ordering': ['-generated_at']},
        ),
    ]
