# Generated by Django 4.2 on 2026-06-26 10:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_finalreport_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=20)),
                ('source_tag', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='report.finalreport')),
            ],
            options={
                'db_table': 'report_action_plans',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='actionplan',
            index=models.Index(fields=['report', 'status'], name='action_report_status_idx'),
        ),
    ]
