# Generated by Django 4.2 on 2026-06-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_roadmapitem_roadmapcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapcache',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roadmapitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
