# Generated by merge resolution on 2026-06-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_actionplan_actionplan_action_report_status_idx'),
        ('report', '0006_finalreport_async_status'),
    ]

    operations = [
    ]
