# Generated by Django 4.2 on 2026-06-08 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('input', '0006_coverletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='JdAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_score', models.FloatField(default=0.0)),
                ('jd_keywords', models.JSONField(default=list)),
                ('resume_analysis', models.JSONField(default=dict)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('cl_points', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jd_analyses', to='input.coverletter')),
                ('jd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jd_analyses', to='input.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jd_analyses', to='input.resumemaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jd_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jd_analysis',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('personality', '인성'), ('technical', '기술·직무'), ('experience', '경험 기반')], max_length=20)),
                ('question_text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('answer', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jd_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='analysis.jdanalysis')),
            ],
            options={
                'db_table': 'analysis_generated_question',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('jd_text', models.TextField()),
                ('resume_text', models.TextField(blank=True)),
                ('cover_letter_text', models.TextField(blank=True)),
                ('jd_keywords', models.JSONField(default=list)),
                ('resume_analysis', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', '분석 대기'), ('analyzing', '분석 중'), ('ready', '완료'), ('failed', '실패')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_sessions', to='input.coverletter')),
                ('jd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_sessions', to='input.jobdescription')),
                ('jd_analysis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='analysis.jdanalysis')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_sessions', to='input.resumemaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analysis_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
