# Generated by Django 4.2 on 2026-06-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_career_level_and_score_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='career_level',
            field=models.CharField(choices=[('entry', '신입'), ('experienced', '경력')], default='entry', max_length=20),
        ),
    ]