# Generated by Django 4.2 on 2026-06-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_move_github_fields_to_jdanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConglomerateCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '대기업집단 계열사',
                'db_table': 'conglomerate_companies',
            },
        ),
        migrations.CreateModel(
            name='IndustryTalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(db_index=True, max_length=100)),
                ('talent_keywords', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '업종별 인재상',
                'db_table': 'industry_talent_profiles',
            },
        ),
        migrations.AddField(
            model_name='analysissession',
            name='company_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='company_type',
            field=models.CharField(blank=True, choices=[('large', '대기업'), ('sme', '중소기업')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='selected_talent_keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
