# Generated by Django 4.2 on 2026-06-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_conglomeratecompany_industrytalentprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedquestion',
            name='question_type',
            field=models.CharField(choices=[('personality', '인성'), ('technical', '기술·직무'), ('experience', '경험 기반'), ('talent', '인재상')], max_length=20),
        ),
    ]
