# Generated by Django 4.2 on 2026-06-04 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('original_text', models.TextField()),
                ('input_method', models.CharField(choices=[('TEXT', 'Text'), ('PDF', 'PDF'), ('URL', 'URL'), ('OCR', 'OCR')], default='TEXT', max_length=10)),
                ('company_summary', models.TextField(blank=True, null=True)),
                ('talent_profile', models.TextField(blank=True, null=True)),
                ('job_requirements', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('analysis_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'input_jobdescription',
                'ordering': ['-created_at'],
            },
        ),
    ]
