# Generated by Django 4.2 on 2026-06-04 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('career_type', models.CharField(choices=[('신입', '신입'), ('경력', '경력')], max_length=10)),
                ('major_type', models.CharField(choices=[('전공', '전공'), ('비전공', '비전공')], max_length=10)),
                ('desired_job', models.CharField(max_length=100)),
                ('career_year', models.PositiveIntegerField(default=0)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'input_userprofile',
                'ordering': ['-updated_at'],
            },
        ),
    ]
