# Generated by Django 6.0.5 on 2026-06-04 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_resumemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeCareer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.CharField(blank=True, max_length=7, null=True)),
                ('end_date', models.CharField(blank=True, max_length=7, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='input.resumemaster')),
            ],
            options={
                'db_table': 'input_resumecareer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('issued_by', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_at', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='input.resumemaster')),
            ],
            options={
                'db_table': 'input_resumecertificate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('degree', models.CharField(choices=[('high_school', 'High School'), ('associate', 'Associate'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('doctor', 'Doctor')], max_length=20)),
                ('start_date', models.CharField(blank=True, max_length=7, null=True)),
                ('end_date', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(choices=[('graduated', 'Graduated'), ('enrolled', 'Enrolled'), ('leave_of_absence', 'Leave of Absence'), ('dropped_out', 'Dropped Out')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='input.resumemaster')),
            ],
            options={
                'db_table': 'input_resumeeducation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='input.resumemaster')),
            ],
            options={
                'db_table': 'input_resumeskill',
                'ordering': ['-created_at'],
            },
        ),
    ]
