# Generated by Django 6.0.5 on 2026-06-04 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_resumecareer_resumecertificate_resumeeducation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('contribution', models.TextField(blank=True, null=True)),
                ('tech_stack', models.JSONField(default=list)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('start_date', models.CharField(blank=True, max_length=7, null=True)),
                ('end_date', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'input_projectexperience',
                'ordering': ['-created_at'],
            },
        ),
    ]
