# Generated by Django 6.0.5 on 2026-06-05 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0005_projectexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to=settings.AUTH_USER_MODEL)),
                ('jd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letters', to='input.jobdescription')),
            ],
            options={
                'db_table': 'input_coverletter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoverLetterItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer_text', models.TextField()),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='input.coverletter')),
            ],
            options={
                'db_table': 'input_coverletteritem',
                'ordering': ['order_index', 'created_at'],
            },
        ),
    ]
