# Generated by Django 4.2 on 2026-06-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0006_coverletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='extracted_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='extraction_confidence',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='is_mock_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='source_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
