# Generated by Django 4.2 on 2026-06-29 03:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0007_jobdescription_extracted_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JDTalentProfile',
            fields=[
                ('jd_talent_profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('OFFICIAL', 'Official'), ('AI_EXTRACTED', 'AI Extracted'), ('USER_DEFINED', 'User Defined'), ('JOB_DEFAULT', 'Job Default'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('source_text', models.TextField(blank=True, null=True)),
                ('custom_summary', models.TextField(blank=True, null=True)),
                ('confirmed_by_user', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_talent_profile', to='input.jobdescription')),
            ],
            options={
                'db_table': 'jd_talent_profiles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TalentProfileCategory',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_code', models.CharField(max_length=50, unique=True)),
                ('category_name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=200)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'talent_profile_categories',
                'ordering': ['display_order', 'category_id'],
            },
        ),
        migrations.CreateModel(
            name='TalentProfileTrait',
            fields=[
                ('trait_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trait_code', models.CharField(max_length=50, unique=True)),
                ('trait_name', models.CharField(max_length=50)),
                ('short_description', models.CharField(max_length=250)),
                ('detailed_description', models.TextField(blank=True, null=True)),
                ('positive_signals', models.JSONField(blank=True, default=list)),
                ('negative_signals', models.JSONField(blank=True, default=list)),
                ('question_templates', models.JSONField(blank=True, default=list)),
                ('followup_templates', models.JSONField(blank=True, default=list)),
                ('evaluation_dimensions', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traits', to='input.talentprofilecategory')),
            ],
            options={
                'db_table': 'talent_profile_traits',
                'ordering': ['category__display_order', 'display_order', 'trait_id'],
            },
        ),
        migrations.CreateModel(
            name='JDTalentProfileItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority_order', models.PositiveSmallIntegerField()),
                ('custom_description', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jd_talent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='input.jdtalentprofile')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_items', to='input.talentprofiletrait')),
            ],
            options={
                'db_table': 'jd_talent_profile_items',
                'ordering': ['priority_order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='jdtalentprofileitem',
            constraint=models.UniqueConstraint(fields=('jd_talent_profile', 'trait'), name='unique_jd_talent_profile_trait'),
        ),
        migrations.AddConstraint(
            model_name='jdtalentprofileitem',
            constraint=models.UniqueConstraint(fields=('jd_talent_profile', 'priority_order'), name='unique_jd_talent_profile_priority'),
        ),
        migrations.AddConstraint(
            model_name='jdtalentprofileitem',
            constraint=models.CheckConstraint(check=models.Q(('priority_order__gte', 1), ('priority_order__lte', 5)), name='jd_talent_profile_priority_1_5'),
        ),
    ]
