# Generated by Django 4.2 on 2026-06-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0009_seed_talent_profile_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdtalentprofileitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
