"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')
load_dotenv(BASE_DIR / '.env.local', override=True)

WORKNET_API_KEY = os.getenv('WORKNET_API_KEY', '')
WORKNET_BASE_URL = os.getenv('WORKNET_BASE_URL', '')

# ===== LangChain / LangSmith =====
LANGCHAIN_TRACING_V2 = os.getenv('LANGCHAIN_TRACING_V2', 'false')
LANGCHAIN_API_KEY    = os.getenv('LANGCHAIN_API_KEY', '')
LANGCHAIN_PROJECT    = os.getenv('LANGCHAIN_PROJECT', 'career-dot-zip')
# ===== AI Chain / OpenAI Settings =====
def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'y', 'on'}


OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# ===== Pinecone =====
PINECONE_API_KEY    = os.getenv('PINECONE_API_KEY', '')
PINECONE_INDEX_NAME = os.getenv('PINECONE_INDEX_NAME', '')
INTERVIEW_AI_CHAIN_ENGINE = os.getenv('INTERVIEW_AI_CHAIN_ENGINE', 'mock').strip().lower()
INTERVIEW_AI_OPENAI_MODEL = os.getenv('INTERVIEW_AI_OPENAI_MODEL', 'gpt-4o')
OPENAI_USE_MOCK = _env_bool("OPENAI_USE_MOCK", False)
INTERVIEW_AI_OPENAI_ENABLE_REAL_CALL = _env_bool(
    'INTERVIEW_AI_OPENAI_ENABLE_REAL_CALL',
    False,
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9cne6oo*j3&x+@c$--or6%i_caj((p(33^#kzc#&tni=2a2x$r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # Local apps
    'apps.accounts',
    'apps.input',
    'apps.interview',
    'apps.evaluation',
    'apps.report',
    'apps.mypage',
    'apps.document',
    'apps.prompt',
    'apps.admin_api',
    'apps.external',
    'apps.question_bank',
    'apps.analysis',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
import dj_database_url

_DB_URL = os.getenv("DATABASE_URL", "").strip()

if _DB_URL:
    _db_config = dj_database_url.config(default=_DB_URL, conn_max_age=600)
    if _db_config.get("ENGINE") == "django.db.backends.mysql":
        # PyMySQL does not accept 'ssl-mode'; convert to ssl={} for Aiven SSL
        _opts = _db_config.get("OPTIONS", {})
        _ssl_mode = _opts.pop("ssl-mode", _opts.pop("ssl_mode", None))
        if _ssl_mode:
            _opts["ssl"] = {}
        _db_config["OPTIONS"] = _opts
    DATABASES = {"default": _db_config}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===== Custom User Model =====
AUTH_USER_MODEL = 'accounts.User'

# ===== CORS Settings =====
# withCredentials(쿠키 기반 refresh) 요청은 와일드카드('*') Origin 과 함께 쓸 수 없다.
# 따라서 특정 Origin 화이트리스트 + credentials 허용으로 구성한다.
# 추가 Origin 은 .env 의 CORS_ALLOWED_ORIGINS(쉼표구분)로 주입한다.
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:5173,http://127.0.0.1:5175",
    ).split(",")
    if o.strip()
]

# ===== DRF Settings =====
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

# ===== Simple JWT Settings =====
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
}

# ===== Speech Evaluation Metrics Configuration =====
SPEECH_CONFIG = {
    "BASE_SCORE": 100.0,
    "FILLER_PENALTY_PER_COUNT": 5.0,        # 필러워드 개당 감점 수치
    "FLOOR_SCORE": 20.0,                    # 최저 방어선 점수
    "EXCESSIVE_FILLER_LIMIT": 6            # 과락 기준 개수
}
# ===== 이메일 발송 설정 =====
# 로컬/개발 기본값은 console backend(터미널 출력). 운영/QA 는 .env 에서 SMTP 로 전환.
# 실제 SMTP 비밀번호 등은 .env(미커밋)에서만 주입한다.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", True)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Career.zip <no-reply@career.zip>")

# 관리자 신규가입 알림 수신 주소. 미설정 시 알림 생략.
ADMIN_NOTIFICATION_EMAIL = os.getenv("ADMIN_NOTIFICATION_EMAIL", "")

# 이메일 인증 링크 구성용 FE base URL
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://localhost:5173")

# 이메일 인증 토큰 만료 (초) — 기본 24시간
EMAIL_VERIFICATION_TOKEN_MAX_AGE = int(
    os.getenv("EMAIL_VERIFICATION_TOKEN_MAX_AGE", str(60 * 60 * 24))
)

# ===== 로깅 (메일/인증 실패 추적) =====

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "apps.accounts": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}
