"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from importlib.util import find_spec
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

try:
    import MySQLdb  # noqa: F401
except ImportError:
    try:
        import pymysql

        pymysql.install_as_MySQLdb()
    except ImportError:
        pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')
load_dotenv(BASE_DIR / '.env.local', override=True)

def _env_int(name: str, default: int) -> int:
    try:
        return int(os.getenv(name, str(default)))
    except (TypeError, ValueError):
        return default


WORKNET_API_KEY = os.getenv('WORKNET_API_KEY', '')
WORKNET_BASE_URL = os.getenv('WORKNET_BASE_URL', '')
JOBS_PROVIDER = os.getenv('JOBS_PROVIDER', 'mock')
MOCK_JOBS_COUNT = _env_int('MOCK_JOBS_COUNT', 10000)
MOCK_JOBS_SEED = _env_int('MOCK_JOBS_SEED', 2026)
MOCK_JOBS_DATA_FILE = os.getenv('MOCK_JOBS_DATA_FILE', '')

# ===== LangChain / LangSmith =====
LANGCHAIN_TRACING_V2  = os.getenv('LANGCHAIN_TRACING_V2', 'false')
LANGCHAIN_API_KEY     = os.getenv('LANGCHAIN_API_KEY', '')
LANGCHAIN_PROJECT     = os.getenv('LANGCHAIN_PROJECT', 'career-dot-zip')
LANGSMITH_ENDPOINT    = os.getenv('LANGSMITH_ENDPOINT', 'https://api.smith.langchain.com')
# ===== AI Chain / OpenAI Settings =====
def _env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'y', 'on'}


OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# ===== Pinecone =====
PINECONE_API_KEY    = os.getenv('PINECONE_API_KEY', '')
PINECONE_INDEX_NAME = os.getenv('PINECONE_INDEX_NAME', '')
INTERVIEW_AI_CHAIN_ENGINE = os.getenv('INTERVIEW_AI_CHAIN_ENGINE', 'mock').strip().lower()
INTERVIEW_AI_OPENAI_MODEL = os.getenv('INTERVIEW_AI_OPENAI_MODEL', 'gpt-4o')
OPENAI_USE_MOCK = _env_bool("OPENAI_USE_MOCK", False)
INTERVIEW_AI_OPENAI_ENABLE_REAL_CALL = _env_bool(
    'INTERVIEW_AI_OPENAI_ENABLE_REAL_CALL',
    False,
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9cne6oo*j3&x+@c$--or6%i_caj((p(33^#kzc#&tni=2a2x$r'

# SECURITY WARNING: don't run with debug turned on in production!
# 운영(prod)에서는 .env 에 DEBUG=False 를 주입한다. 로컬 기본값은 True.
DEBUG = _env_bool('DEBUG', True)

# SECURITY: SECRET_KEY 는 .env 의 값을 우선 사용한다.
# (.env 에 SECRET_KEY 미설정 시에만 위에서 정의된 로컬 개발용 기본값을 사용)
SECRET_KEY = os.getenv('SECRET_KEY', SECRET_KEY)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # Local apps
    'apps.accounts',
    'apps.input',
    'apps.interview',
    'apps.evaluation',
    'apps.report',
    'apps.mypage',
    'apps.document',
    'apps.prompt',
    'apps.admin_api',
    'apps.points',
    'apps.external',
    'apps.question_bank',
    'apps.analysis',
]

if find_spec('django_apscheduler') is not None:
    INSTALLED_APPS.append('django_apscheduler')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
import dj_database_url

_DB_URL = os.getenv("DATABASE_URL", "").strip()

if _DB_URL:
    _db_config = dj_database_url.config(default=_DB_URL, conn_max_age=600)
    if _db_config.get("ENGINE") == "django.db.backends.mysql":
        # PyMySQL does not accept 'ssl-mode'; convert to ssl={} for Aiven SSL
        _opts = _db_config.get("OPTIONS", {})
        _ssl_mode = _opts.pop("ssl-mode", _opts.pop("ssl_mode", None))
        if _ssl_mode:
            _opts["ssl"] = {}
        _db_config["OPTIONS"] = _opts
    DATABASES = {"default": _db_config}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        # 이메일/이름이 포함된 비밀번호 차단 (Custom User 는 name 필드 사용)
        'OPTIONS': {'user_attributes': ('email', 'name')},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        # 영문/숫자/특수문자 조합 + 동일문자 3연속 금지 (qwer1234 등 차단)
        'NAME': 'apps.accounts.validators.PasswordComplexityValidator',
        'OPTIONS': {'min_length': 8},
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ===== S3 / 미디어 스토리지 =====
AWS_S3_BUCKET = os.getenv('AWS_S3_BUCKET_NAME', '')

if AWS_S3_BUCKET:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_STORAGE_BUCKET_NAME = AWS_S3_BUCKET
    AWS_S3_REGION_NAME = os.getenv('AWS_S3_REGION_NAME', 'ap-northeast-2')
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    MEDIA_URL = f'https://{AWS_S3_BUCKET}.s3.amazonaws.com/'
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===== Custom User Model =====
AUTH_USER_MODEL = 'accounts.User'

# ===== CORS Settings =====
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:5173,http://localhost:5174,http://localhost:5175,http://127.0.0.1:5173,http://127.0.0.1:5174,http://127.0.0.1:5175",
    ).split(",")
    if origin.strip()
]

# ===== CSRF (운영 HTTPS / 크로스도메인 대비) =====
# 운영에서는 .env 의 CSRF_TRUSTED_ORIGINS 에 프론트 도메인을 등록한다. (예: https://app.career.zip)
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

# ===== refresh_token 쿠키 보안 (로컬/운영 분리) =====
# 로컬(HTTP): SECURE=False, SAMESITE=Lax.
# 운영(HTTPS): .env 로 REFRESH_COOKIE_SECURE=True 주입. 프론트/백 도메인이 다르면 SAMESITE=None 필요.
REFRESH_COOKIE_SECURE = _env_bool("REFRESH_COOKIE_SECURE", False)
REFRESH_COOKIE_SAMESITE = os.getenv("REFRESH_COOKIE_SAMESITE", "Lax")
REFRESH_COOKIE_PATH = os.getenv("REFRESH_COOKIE_PATH", "/")
REFRESH_COOKIE_DOMAIN = os.getenv("REFRESH_COOKIE_DOMAIN") or None

# ===== DRF Settings =====
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

# ===== Simple JWT Settings =====
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
}

# ===== Speech Evaluation Metrics Configuration =====
SPEECH_CONFIG = {
    # QA 피드백 반영: 필러/pause 없는 발화자가 99점 받는 문제 보정.
    # BASE_SCORE=80 → 완벽한 전달력도 80점이 상한(면접 특성상 100점은 비현실적).
    "BASE_SCORE": 80.0,
    "FILLER_PENALTY_PER_COUNT": 5.0,        # 필러워드 개당 감점 수치
    "FLOOR_SCORE": 20.0,                    # 최저 방어선 점수
    "EXCESSIVE_FILLER_LIMIT": 6,            # 과락 기준 개수
    # -- E7.6 휴지(pause) 패턴 파라미터 --
    "SPEECH_RATE_WORDS_PER_SEC": 3.0,       # 한국어 평균 발화 속도(단어/초)
    "PAUSE_DURATION_SEC": 3.0,              # long_pause 1회 추정 길이(초)
    "PAUSE_RATIO_THRESHOLD": 0.30,          # 이 비율 초과 시 비례 감점 시작
    "PAUSE_RATIO_PENALTY_SCALE": 50.0,      # 초과 비율(소수)에 곱하는 감점 계수
    "PAUSE_SEVERITY_PENALTY": {             # severity별 기본 감점
        "none": 0.0, "minimal": 0.0, "moderate": 5.0, "high": 12.0, "critical": 22.0,
    },
    "PAUSE_SEVERITY_THRESHOLDS": {          # long_pause_count 분류 경계(이하 기준)
        "minimal": 1, "moderate": 3, "high": 6,
    },
}
# ===== 이메일 발송 설정 =====
# 로컬/개발 기본값은 console backend(터미널 출력). 운영/QA 는 .env 에서 SMTP 로 전환.
# 실제 SMTP 비밀번호 등은 .env(미커밋)에서만 주입한다.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", False)
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "Career.zip <no-reply@career.zip>")

# 관리자 신규가입 알림 수신 주소. 미설정 시 알림 생략.
ADMIN_NOTIFICATION_EMAIL = os.getenv("ADMIN_NOTIFICATION_EMAIL", "")

# 이메일 인증 링크 구성용 FE base URL
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "http://localhost:5173")

# 이메일 인증 토큰 만료 (초) — 기본 24시간
EMAIL_VERIFICATION_TOKEN_MAX_AGE = int(
    os.getenv("EMAIL_VERIFICATION_TOKEN_MAX_AGE", str(60 * 60 * 24))
)

# ===== 이메일 인증번호(코드) 정책 =====
# 외부 메일 서비스의 수신 지연 가능성을 고려해 만료를 10분(600초)으로 둔다. (보안상 30분 이상은 비권장)
# 재발송 쿨다운 60초 / 최대 시도 5회 유지. 모두 .env 로 재정의 가능.
EMAIL_CODE_TTL_SECONDS = int(os.getenv("EMAIL_CODE_TTL_SECONDS", "600"))
EMAIL_CODE_MAX_ATTEMPTS = int(os.getenv("EMAIL_CODE_MAX_ATTEMPTS", "5"))
EMAIL_CODE_RESEND_COOLDOWN_SECONDS = int(
    os.getenv("EMAIL_CODE_RESEND_COOLDOWN_SECONDS", "60")
)

# ===== 로깅 (메일/인증 실패 추적) =====

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "apps.accounts": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}
