# Generated by Django 4.2 on 2026-06-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
