# Generated by Django 4.2 on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_uploadeddocument_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file_type',
            field=models.CharField(
                choices=[('pdf', 'PDF'), ('docx', 'DOCX')],
                max_length=20,
            ),
        ),
    ]
