# Generated by Django 4.2.30 on 2026-06-18 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_llmusagelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LlmUsageLog',
        ),
    ]
