# Generated by Django 4.2 on 2026-06-26 06:12

from django.db import migrations


class Migration(migrations.Migration):
    # origin/develop's 0004_llmusagelog creates the llm_usage_log table.
    # This feature-branch migration only preserves migration history.

    dependencies = [
        ('admin_api', '0003_delete_llmusagelog'),
    ]

    operations = []
