# Generated by merge resolution on 2026-06-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0004_restore_llm_usage_log"),
        ("admin_api", "0005_apierrorlog"),
    ]

    operations = []
