# Generated by Django 4.2 on 2026-06-05 07:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_category', models.CharField(db_index=True, default='ICT', max_length=100)),
                ('question_text', models.TextField()),
                ('answer_example', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('technical', 'Technical'), ('personality', 'Personality'), ('job', 'Job')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('keywords', models.JSONField(default=list)),
                ('source', models.CharField(db_index=True, default='aihub', max_length=50)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('source_ref', models.CharField(blank=True, max_length=255)),
                ('raw_metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question_bank_items',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='questionbankitem',
            index=models.Index(fields=['job_category', 'question_type', 'difficulty'], name='qbank_job_type_diff_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankitem',
            index=models.Index(fields=['source', 'source_file'], name='qbank_source_file_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionbankitem',
            constraint=models.UniqueConstraint(fields=('source', 'source_ref'), name='unique_question_bank_source_ref'),
        ),
    ]
