# Generated by Django 4.2 on 2026-06-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbankitem',
            name='question_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='questionbankitem',
            constraint=models.UniqueConstraint(fields=('source', 'source_file', 'question_hash'), name='unique_question_bank_source_file_hash'),
        ),
    ]
