# Generated by Django 6.0.5 on 2026-06-05 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('input', '0005_projectexperience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interview_type', models.CharField(choices=[('technical', 'Technical'), ('personality', 'Personality'), ('comprehensive', 'Comprehensive')], max_length=20)),
                ('persona', models.CharField(choices=[('coach', 'Coach'), ('practical', 'Practical'), ('verifier', 'Verifier'), ('pressure', 'Pressure')], max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('total_question_count', models.PositiveIntegerField(default=3)),
                ('current_question_index', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='input.coverletter')),
                ('jd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='input.jobdescription')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='input.resumemaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
