# Generated by Django 6.0.5 on 2026-06-05 00:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('main', 'Main'), ('follow_up', 'Follow Up')], default='main', max_length=20)),
                ('question_text', models.TextField()),
                ('source_type', models.CharField(choices=[('jd', 'JD'), ('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('project', 'Project'), ('profile', 'Profile'), ('general', 'General')], default='general', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.interviewsession')),
            ],
            options={
                'db_table': 'interview_questions',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddConstraint(
            model_name='interviewquestion',
            constraint=models.UniqueConstraint(fields=('session', 'order_index'), name='unique_session_order_index'),
        ),
    ]
