# Generated by Django 6.0.5 on 2026-06-04 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interviewanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_questions', to='interview.interviewquestion'),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='source_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_questions', to='interview.interviewanswer'),
        ),
    ]
