# Generated by Django 4.2 on 2026-06-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_interviewquestion_parent_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewanswer',
            name='answer_source',
            field=models.CharField(choices=[('text', '텍스트'), ('stt', '음성 인식')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('main', '기본 질문'), ('follow_up', '꼬리질문')], default='main', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='interview_type',
            field=models.CharField(choices=[('technical', '기술 면접'), ('personality', '인성 면접'), ('comprehensive', '종합 면접')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='persona',
            field=models.CharField(choices=[('coach', '코치형'), ('practical', '실무형'), ('verifier', '검증형'), ('pressure', '압박형')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='status',
            field=models.CharField(choices=[('created', '생성됨'), ('in_progress', '진행 중'), ('completed', '완료'), ('cancelled', '취소')], default='created', max_length=20),
        ),
    ]
