# Generated by Django 4.2 on 2026-06-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_alter_interviewanswer_answer_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='interview_mode',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], default='text', max_length=10),
        ),
    ]
