# Generated by Django 4.2 on 2026-06-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_interviewsession_interview_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='long_pause_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='speech_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='stt_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='total_pause_duration',
            field=models.FloatField(default=0),
        ),
    ]
