# Generated by Django 4.2.30 on 2026-06-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_remove_pressure_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='question_category',
            field=models.CharField(choices=[('technical', 'Technical'), ('personality', 'Personality'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
