# Generated by Django 4.2 on 2026-06-26 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0010_interviewquestion_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardrailEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('G0', 'Allow'), ('G1', 'Guide'), ('G2', 'Warn'), ('G3', 'Block Input'), ('G4', 'Sensitive Or Unsafe'), ('G5', 'End Session')], max_length=2)),
                ('action', models.CharField(choices=[('ALLOW', 'Allow'), ('GUIDE', 'Guide'), ('WARN', 'Warn'), ('BLOCK_INPUT', 'Block Input'), ('END_SESSION', 'End Session')], max_length=20)),
                ('reason_code', models.CharField(max_length=80)),
                ('masked_excerpt', models.CharField(blank=True, default='', max_length=240)),
                ('endpoint', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardrail_events', to='interview.interviewanswer')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardrail_events', to='interview.interviewquestion')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guardrail_events', to='interview.interviewsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardrail_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guardrail_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='guardrailevent',
            index=models.Index(fields=['category', 'created_at'], name='guardrail_cat_created_idx'),
        ),
        migrations.AddIndex(
            model_name='guardrailevent',
            index=models.Index(fields=['user', 'created_at'], name='guardrail_user_created_idx'),
        ),
    ]
