# Generated by Django 4.2 on 2026-06-26 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview', '0011_guardrailevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('interview_type', models.CharField(choices=[('technical', '기술 면접'), ('personality', '인성 면접'), ('comprehensive', '종합 면접')], default='technical', max_length=20)),
                ('mix', models.JSONField(blank=True, default=dict)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('prompt_version_snapshot', models.JSONField(blank=True, default=dict)),
                ('generation_model', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('FAILED', 'Failed')], default='READY', max_length=20)),
                ('is_fallback', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interview_question_packs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='guardrailevent',
            name='direction',
            field=models.CharField(choices=[('USER_TO_AI', 'User To AI'), ('AI_TO_USER', 'AI To User')], default='USER_TO_AI', max_length=20),
        ),
        migrations.AddField(
            model_name='guardrailevent',
            name='retention_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='guardrailevent',
            name='rule_source',
            field=models.CharField(default='RULE', max_length=20),
        ),
        migrations.AddField(
            model_name='guardrailevent',
            name='stage',
            field=models.CharField(choices=[('SIGNUP', 'Signup'), ('MYPAGE', 'Mypage'), ('INTERVIEW', 'Interview'), ('REPORT', 'Report')], default='INTERVIEW', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='prompt_version_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='guardrailevent',
            name='action',
            field=models.CharField(choices=[('ALLOW', 'Allow'), ('GUIDE', 'Guide'), ('WARN', 'Warn'), ('BLOCK_INPUT', 'Block Input'), ('SKIP_FOLLOWUP', 'Skip Follow-up'), ('END_SESSION', 'End Session'), ('REQUIRE_ADMIN_REVIEW', 'Require Admin Review')], max_length=20),
        ),
        migrations.AlterField(
            model_name='guardrailevent',
            name='category',
            field=models.CharField(choices=[('G0', 'Normal'), ('G1', 'Low Quality'), ('G2', 'Repeated Or Irrelevant'), ('G3', 'Sensitive Or Injection'), ('G4', 'Harmful Or Illegal'), ('G5', 'Automation Or Privilege Abuse')], max_length=2),
        ),
        migrations.AddIndex(
            model_name='guardrailevent',
            index=models.Index(fields=['stage', 'direction', 'created_at'], name='guardrail_stage_dir_idx'),
        ),
        migrations.AddField(
            model_name='questionpack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_packs', to=settings.AUTH_USER_MODEL),
        ),
    ]
